<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGhqAz8t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGhqAz8t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGhqAz8t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGhqAz8t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGhqAz8t\App_KernelDevDebugContainer([
    'container.build_hash' => 'GhqAz8t',
    'container.build_id' => '6828c12d',
    'container.build_time' => 1583248308,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGhqAz8t');
